### ISSUE TITLE
Kotlin 

### ISSUE THREAD

**Issue by ravagegamerofficial** [JakeJMattson/EmbedBot#1]
Well i was just playing with the source code for the sake of learning Kotlin Discord Wrapper so i have recently found that your bot version .10 has auto message deletion after execution well i just want to learn how that work basically what event you trigger and all.
hope this could be possible for you to answer

-Rohan

**Comment by JakeJMattson** [comment]
Add me on Discord and I will be happy to explain it - [JakeyWakey#1569](https://discordapp.com/users/254786431656919051/)
